global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:

- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
    

- job_name: 'spring boot scrape'
  metrics_path: '/actuator/prometheus'
  scrape_interval: 5s
  static_configs:
    - targets: ['trifecta-device-registry:8085']


- job_name: 'emqx'
  metrics_path: '/api/v5/prometheus/stats'
  scrape_interval: 5s
  honor_labels: true
  static_configs:
    - targets: ['messaging-mqtt:18083']


- job_name: 'postgres'
  metrics_path: '/metrics'
  scrape_interval: 5s
  honor_labels: true
  static_configs:
    - targets: ['postgres-exporter:9187']


- job_name: 'kafka'
  metrics_path: '/metrics'
  scrape_interval: 5s
  honor_labels: true
  static_configs:
    - targets: ['kafka-exporter:9308']